package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class answer_log extends BaseDomain {//BaseDomainÔÚCommon.jarÖÐ·â×°
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.answer_id
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer answerId;

    private Integer askId;
    
    private Integer studentId;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.group_id
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private String groupId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.answer_time
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Date answerTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.right
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private String isRight;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.type
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.is_a
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer isA;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.is_b
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer isB;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.is_c
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer isC;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.is_d
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer isD;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.is_e
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer isE;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.is_f
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer isF;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.is_g
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer isG;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.answer_content
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private String answerContent;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column answer_log.yes_no_answer
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    private Integer yesNoAnswer;
    private String picDraw;
    public String getPicDraw() {
		return picDraw;
	}

	public void setPicDraw(String picDraw) {
		this.picDraw = picDraw;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.answer_id
     *
     * @return the value of answer_log.answer_id
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.answer_id
     *
     * @param answerId the value for answer_log.answer_id
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.group_id
     *
     * @return the value of answer_log.group_id
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public String getGroupId() {
        return groupId;
    }

    public Integer getAskId() {
		return askId;
	}

	public void setAskId(Integer askId) {
		this.askId = askId;
	}

	public Integer getStudentId() {
		return studentId;
	}

	public void setStudentId(Integer studentId) {
		this.studentId = studentId;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.group_id
     *
     * @param groupId the value for answer_log.group_id
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.answer_time
     *
     * @return the value of answer_log.answer_time
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Date getAnswerTime() {
        return answerTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.answer_time
     *
     * @param answerTime the value for answer_log.answer_time
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setAnswerTime(Date answerTime) {
        this.answerTime = answerTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.right
     *
     * @return the value of answer_log.right
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.type
     *
     * @return the value of answer_log.type
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public String getType() {
        return type;
    }

    public String getIsRight() {
		return isRight;
	}

	public void setIsRight(String isRight) {
		this.isRight = isRight;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.type
     *
     * @param type the value for answer_log.type
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.is_a
     *
     * @return the value of answer_log.is_a
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getIsA() {
        return isA;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.is_a
     *
     * @param isA the value for answer_log.is_a
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setIsA(Integer isA) {
        this.isA = isA;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.is_b
     *
     * @return the value of answer_log.is_b
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getIsB() {
        return isB;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.is_b
     *
     * @param isB the value for answer_log.is_b
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setIsB(Integer isB) {
        this.isB = isB;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.is_c
     *
     * @return the value of answer_log.is_c
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getIsC() {
        return isC;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.is_c
     *
     * @param isC the value for answer_log.is_c
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setIsC(Integer isC) {
        this.isC = isC;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.is_d
     *
     * @return the value of answer_log.is_d
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getIsD() {
        return isD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.is_d
     *
     * @param isD the value for answer_log.is_d
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setIsD(Integer isD) {
        this.isD = isD;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.is_e
     *
     * @return the value of answer_log.is_e
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getIsE() {
        return isE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.is_e
     *
     * @param isE the value for answer_log.is_e
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setIsE(Integer isE) {
        this.isE = isE;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.is_f
     *
     * @return the value of answer_log.is_f
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getIsF() {
        return isF;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.is_f
     *
     * @param isF the value for answer_log.is_f
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setIsF(Integer isF) {
        this.isF = isF;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.is_g
     *
     * @return the value of answer_log.is_g
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getIsG() {
        return isG;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.is_g
     *
     * @param isG the value for answer_log.is_g
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setIsG(Integer isG) {
        this.isG = isG;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.answer_content
     *
     * @return the value of answer_log.answer_content
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.answer_content
     *
     * @param answerContent the value for answer_log.answer_content
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column answer_log.yes_no_answer
     *
     * @return the value of answer_log.yes_no_answer
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public Integer getYesNoAnswer() {
        return yesNoAnswer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column answer_log.yes_no_answer
     *
     * @param yesNoAnswer the value for answer_log.yes_no_answer
     *
     * @abatorgenerated Thu Jan 15 08:52:13 CST 2015
     */
    public void setYesNoAnswer(Integer yesNoAnswer) {
        this.yesNoAnswer = yesNoAnswer;
    }
}