package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class ask_log extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ask_log.ask_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    private Integer askId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ask_log.cource_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    private Integer courceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ask_log.item_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    private Integer itemId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ask_log.teacher_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ask_log.ask_time
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    private Date askTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ask_log.ask_type
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    private Integer askType;
    
    private Integer finishType;
    
    private Integer robUserId;
    private Integer groupId;
    private Integer isRight;
    
    private String question;
    private String name;
    private Integer sumNum;
    private Integer jwjdNum;
    private Integer qdNum;
    private Integer trNum;
    private Integer tzNum;
    private String departmentId;
    private String departmentName;
    private String className;
    private String subjectName;
    private Integer classId;
    private String userName;
    private Integer rightNum;
    private String percent;

    public String getPercent() {
		return percent;
	}

	public void setPercent(String percent) {
		this.percent = percent;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Integer getRightNum() {
		return rightNum;
	}

	public void setRightNum(Integer rightNum) {
		this.rightNum = rightNum;
	}

	public Integer getClassId() {
		return classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getSubjectName() {
		return subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Integer getSumNum() {
		return sumNum;
	}

	public void setSumNum(Integer sumNum) {
		this.sumNum = sumNum;
	}

	public Integer getJwjdNum() {
		return jwjdNum;
	}

	public void setJwjdNum(Integer jwjdNum) {
		this.jwjdNum = jwjdNum;
	}

	public Integer getQdNum() {
		return qdNum;
	}

	public void setQdNum(Integer qdNum) {
		this.qdNum = qdNum;
	}

	public Integer getTrNum() {
		return trNum;
	}

	public void setTrNum(Integer trNum) {
		this.trNum = trNum;
	}

	public Integer getTzNum() {
		return tzNum;
	}

	public void setTzNum(Integer tzNum) {
		this.tzNum = tzNum;
	}

	public String getQuestion() {
		return question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getFinishType() {
		return finishType;
	}

	public void setFinishType(Integer finishType) {
		this.finishType = finishType;
	}

	public Integer getRobUserId() {
		return robUserId;
	}

	public Integer getIsRight() {
		return isRight;
	}

	public void setIsRight(Integer isRight) {
		this.isRight = isRight;
	}

	public void setRobUserId(Integer robUserId) {
		this.robUserId = robUserId;
	}

	public Integer getGroupId() {
		return groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ask_log.ask_id
     *
     * @return the value of ask_log.ask_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public Integer getAskId() {
        return askId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ask_log.ask_id
     *
     * @param askId the value for ask_log.ask_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public void setAskId(Integer askId) {
        this.askId = askId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ask_log.cource_id
     *
     * @return the value of ask_log.cource_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public Integer getCourceId() {
        return courceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ask_log.cource_id
     *
     * @param courceId the value for ask_log.cource_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public void setCourceId(Integer courceId) {
        this.courceId = courceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ask_log.item_id
     *
     * @return the value of ask_log.item_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ask_log.item_id
     *
     * @param itemId the value for ask_log.item_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ask_log.teacher_id
     *
     * @return the value of ask_log.teacher_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ask_log.teacher_id
     *
     * @param teacherId the value for ask_log.teacher_id
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ask_log.ask_time
     *
     * @return the value of ask_log.ask_time
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public Date getAskTime() {
        return askTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ask_log.ask_time
     *
     * @param askTime the value for ask_log.ask_time
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public void setAskTime(Date askTime) {
        this.askTime = askTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ask_log.ask_type
     *
     * @return the value of ask_log.ask_type
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public Integer getAskType() {
        return askType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ask_log.ask_type
     *
     * @param askType the value for ask_log.ask_type
     *
     * @abatorgenerated Fri Dec 19 08:35:31 CST 2014
     */
    public void setAskType(Integer askType) {
        this.askType = askType;
    }
}