package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class attendance extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column attendance.attendance_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    private Integer attendanceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column attendance.student_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    private Integer studentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column attendance.cource_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    private Integer courceId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column attendance.create_time
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    private Date createTime;
    private String departmentId;
    private String departmentName;
    private Integer classId;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column attendance.absent
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    private String absent;
    
    private String className;
    private String subjectName;
    private Integer num;
    private String createTime1;
    private Integer leaveNum;
    private Integer sumNum;
    private Integer wdNum;
    private String percent;
    private String searchType;
    private String tubiaoType;

    public String getSearchType() {
		return searchType;
	}

	public void setSearchType(String searchType) {
		this.searchType = searchType;
	}

	public String getTubiaoType() {
		return tubiaoType;
	}

	public void setTubiaoType(String tubiaoType) {
		this.tubiaoType = tubiaoType;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getPercent() {
		return percent;
	}

	public String getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	public Integer getClassId() {
		return classId;
	}

	public void setClassId(Integer classId) {
		this.classId = classId;
	}

	public void setPercent(String percent) {
		this.percent = percent;
	}

	public Integer getWdNum() {
		return wdNum;
	}

	public void setWdNum(Integer wdNum) {
		this.wdNum = wdNum;
	}

	public Integer getSumNum() {
		return sumNum;
	}

	public void setSumNum(Integer sumNum) {
		this.sumNum = sumNum;
	}

	public Integer getLeaveNum() {
		return leaveNum;
	}

	public void setLeaveNum(Integer leaveNum) {
		this.leaveNum = leaveNum;
	}

	public String getCreateTime1() {
		return createTime1;
	}

	public void setCreateTime1(String createTime1) {
		this.createTime1 = createTime1;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getSubjectName() {
		return subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Integer getNum() {
		return num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column attendance.attendance_id
     *
     * @return the value of attendance.attendance_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public Integer getAttendanceId() {
        return attendanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column attendance.attendance_id
     *
     * @param attendanceId the value for attendance.attendance_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public void setAttendanceId(Integer attendanceId) {
        this.attendanceId = attendanceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column attendance.student_id
     *
     * @return the value of attendance.student_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column attendance.student_id
     *
     * @param studentId the value for attendance.student_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column attendance.cource_id
     *
     * @return the value of attendance.cource_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public Integer getCourceId() {
        return courceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column attendance.cource_id
     *
     * @param courceId the value for attendance.cource_id
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public void setCourceId(Integer courceId) {
        this.courceId = courceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column attendance.create_time
     *
     * @return the value of attendance.create_time
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column attendance.create_time
     *
     * @param createTime the value for attendance.create_time
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column attendance.absent
     *
     * @return the value of attendance.absent
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public String getAbsent() {
        return absent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column attendance.absent
     *
     * @param absent the value for attendance.absent
     *
     * @abatorgenerated Mon Jan 26 11:57:13 CST 2015
     */
    public void setAbsent(String absent) {
        this.absent = absent;
    }
}