package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;

public class class_section extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column class_section.class_section_id
     *
     * @abatorgenerated Tue Feb 03 08:42:08 CST 2015
     */
    private Integer classSectionId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column class_section.from_time
     *
     * @abatorgenerated Tue Feb 03 08:42:08 CST 2015
     */
    private String fromTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column class_section.end_time
     *
     * @abatorgenerated Tue Feb 03 08:42:08 CST 2015
     */
    private String toTime;

    public String getToTime() {
		return toTime;
	}

	public void setToTime(String toTime) {
		this.toTime = toTime;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column class_section.class_section_id
     *
     * @return the value of class_section.class_section_id
     *
     * @abatorgenerated Tue Feb 03 08:42:08 CST 2015
     */
    public Integer getClassSectionId() {
        return classSectionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column class_section.class_section_id
     *
     * @param classSectionId the value for class_section.class_section_id
     *
     * @abatorgenerated Tue Feb 03 08:42:08 CST 2015
     */
    public void setClassSectionId(Integer classSectionId) {
        this.classSectionId = classSectionId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column class_section.from_time
     *
     * @return the value of class_section.from_time
     *
     * @abatorgenerated Tue Feb 03 08:42:08 CST 2015
     */
    public String getFromTime() {
        return fromTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column class_section.from_time
     *
     * @param fromTime the value for class_section.from_time
     *
     * @abatorgenerated Tue Feb 03 08:42:08 CST 2015
     */
    public void setFromTime(String fromTime) {
        this.fromTime = fromTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column class_section.end_time
     *
     * @return the value of class_section.end_time
     *
     * @abatorgenerated Tue Feb 03 08:42:08 CST 2015
     */
}