package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class course extends BaseDomain {
    private Integer courceId;//对应一门课程id名称
    private Integer classId;//对应班级名称，eg:计算机A班     对应t_class表
    private String subjectId;//对应一门课程名称，eg:语文id，    对应subject表
    private String subjectName;//对应一门课程的名称：eg：语文
    private Date fromTime;//课程开始时间
    private Date endTime;//课程结束时间
    private Integer address;//目前没有用到
    private Integer userId;//目前没有用到
    private Integer agentUserId;//上课老师id，与t_user表的user_id一致
    private Integer classSectionId;//上课时间段，对应class_section表的classSectionId
    
    public String getSubjectName() {
		return subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Integer getAgentUserId() {
		return agentUserId;
	}

	public void setAgentUserId(Integer agentUserId) {
		this.agentUserId = agentUserId;
	}

	public Integer getClassSectionId() {
		return classSectionId;
	}

	public void setClassSectionId(Integer classSectionId) {
		this.classSectionId = classSectionId;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column course.cource_id
     *
     * @return the value of course.cource_id
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public Integer getCourceId() {
        return courceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column course.cource_id
     *
     * @param courceId the value for course.cource_id
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public void setCourceId(Integer courceId) {
        this.courceId = courceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column course.class_id
     *
     * @return the value of course.class_id
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column course.class_id
     *
     * @param classId the value for course.class_id
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column course.subject_id
     *
     * @return the value of course.subject_id
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column course.subject_id
     *
     * @param subjectId the value for course.subject_id
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public void setSubjectId(String subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column course.from_time
     *
     * @return the value of course.from_time
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public Date getFromTime() {
        return fromTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column course.from_time
     *
     * @param fromTime the value for course.from_time
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public void setFromTime(Date fromTime) {
        this.fromTime = fromTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column course.end_time
     *
     * @return the value of course.end_time
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column course.end_time
     *
     * @param endTime the value for course.end_time
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column course.address
     *
     * @return the value of course.address
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public Integer getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column course.address
     *
     * @param address the value for course.address
     *
     * @abatorgenerated Thu Jan 15 15:15:44 CST 2015
     */
    public void setAddress(Integer address) {
        this.address = address;
    }
}