package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;

public class department extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column department.department_id
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    private Integer departmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column department.department_name
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    private String departmentName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column department.parent_department_id
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    private Integer parentDepartmentId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column department.department_id
     *
     * @return the value of department.department_id
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column department.department_id
     *
     * @param departmentId the value for department.department_id
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column department.department_name
     *
     * @return the value of department.department_name
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column department.department_name
     *
     * @param departmentName the value for department.department_name
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column department.parent_department_id
     *
     * @return the value of department.parent_department_id
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    public Integer getParentDepartmentId() {
        return parentDepartmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column department.parent_department_id
     *
     * @param parentDepartmentId the value for department.parent_department_id
     *
     * @abatorgenerated Thu Jan 22 15:36:23 CST 2015
     */
    public void setParentDepartmentId(Integer parentDepartmentId) {
        this.parentDepartmentId = parentDepartmentId;
    }
}