package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class JXHD_shijuan extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_shijuan.ID
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_shijuan.chuti_man
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    private String shijuanName;
    private Integer chutiMan;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_shijuan.chuti_time
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    private Date chutiTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_shijuan.datiType
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    private String datitype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_shijuan.status
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    private String status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_shijuan.questionOrders
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    private String questionorders;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_shijuan.ID
     *
     * @return the value of JXHD_shijuan.ID
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_shijuan.ID
     *
     * @param id the value for JXHD_shijuan.ID
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_shijuan.chuti_man
     *
     * @return the value of JXHD_shijuan.chuti_man
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public Integer getChutiMan() {
        return chutiMan;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_shijuan.chuti_man
     *
     * @param chutiMan the value for JXHD_shijuan.chuti_man
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public void setChutiMan(Integer chutiMan) {
        this.chutiMan = chutiMan;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_shijuan.chuti_time
     *
     * @return the value of JXHD_shijuan.chuti_time
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public Date getChutiTime() {
        return chutiTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_shijuan.chuti_time
     *
     * @param chutiTime the value for JXHD_shijuan.chuti_time
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public void setChutiTime(Date chutiTime) {
        this.chutiTime = chutiTime;
    }

    public String getShijuanName() {
		return shijuanName;
	}

	public void setShijuanName(String shijuanName) {
		this.shijuanName = shijuanName;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_shijuan.datiType
     *
     * @return the value of JXHD_shijuan.datiType
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public String getDatitype() {
        return datitype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_shijuan.datiType
     *
     * @param datitype the value for JXHD_shijuan.datiType
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public void setDatitype(String datitype) {
        this.datitype = datitype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_shijuan.status
     *
     * @return the value of JXHD_shijuan.status
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_shijuan.status
     *
     * @param status the value for JXHD_shijuan.status
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_shijuan.questionOrders
     *
     * @return the value of JXHD_shijuan.questionOrders
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public String getQuestionorders() {
        return questionorders;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_shijuan.questionOrders
     *
     * @param questionorders the value for JXHD_shijuan.questionOrders
     *
     * @abatorgenerated Tue Oct 28 11:12:44 CST 2014
     */
    public void setQuestionorders(String questionorders) {
        this.questionorders = questionorders;
    }
}