package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;

public class JXHD_SEL extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.ID
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.ChoiceA
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String choicea;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.ChoiceB
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String choiceb;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.ChoiceC
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String choicec;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.ChoiceD
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String choiced;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.answer
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String answer;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.score
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private Double score;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.teacherID
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private Integer teacherid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.QuesDifficult
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String quesdifficult;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.questionType
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String questiontype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.questionOrders
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String questionorders;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_SEL.question
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    private String question;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.ID
     *
     * @return the value of JXHD_SEL.ID
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.ID
     *
     * @param id the value for JXHD_SEL.ID
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.ChoiceA
     *
     * @return the value of JXHD_SEL.ChoiceA
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getChoicea() {
        return choicea;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.ChoiceA
     *
     * @param choicea the value for JXHD_SEL.ChoiceA
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setChoicea(String choicea) {
        this.choicea = choicea;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.ChoiceB
     *
     * @return the value of JXHD_SEL.ChoiceB
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getChoiceb() {
        return choiceb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.ChoiceB
     *
     * @param choiceb the value for JXHD_SEL.ChoiceB
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setChoiceb(String choiceb) {
        this.choiceb = choiceb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.ChoiceC
     *
     * @return the value of JXHD_SEL.ChoiceC
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getChoicec() {
        return choicec;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.ChoiceC
     *
     * @param choicec the value for JXHD_SEL.ChoiceC
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setChoicec(String choicec) {
        this.choicec = choicec;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.ChoiceD
     *
     * @return the value of JXHD_SEL.ChoiceD
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getChoiced() {
        return choiced;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.ChoiceD
     *
     * @param choiced the value for JXHD_SEL.ChoiceD
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setChoiced(String choiced) {
        this.choiced = choiced;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.answer
     *
     * @return the value of JXHD_SEL.answer
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.answer
     *
     * @param answer the value for JXHD_SEL.answer
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.score
     *
     * @return the value of JXHD_SEL.score
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.score
     *
     * @param score the value for JXHD_SEL.score
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.teacherID
     *
     * @return the value of JXHD_SEL.teacherID
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.teacherID
     *
     * @param teacherid the value for JXHD_SEL.teacherID
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.QuesDifficult
     *
     * @return the value of JXHD_SEL.QuesDifficult
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getQuesdifficult() {
        return quesdifficult;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.QuesDifficult
     *
     * @param quesdifficult the value for JXHD_SEL.QuesDifficult
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setQuesdifficult(String quesdifficult) {
        this.quesdifficult = quesdifficult;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.questionType
     *
     * @return the value of JXHD_SEL.questionType
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getQuestiontype() {
        return questiontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.questionType
     *
     * @param questiontype the value for JXHD_SEL.questionType
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setQuestiontype(String questiontype) {
        this.questiontype = questiontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.questionOrders
     *
     * @return the value of JXHD_SEL.questionOrders
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getQuestionorders() {
        return questionorders;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.questionOrders
     *
     * @param questionorders the value for JXHD_SEL.questionOrders
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setQuestionorders(String questionorders) {
        this.questionorders = questionorders;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_SEL.question
     *
     * @return the value of JXHD_SEL.question
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_SEL.question
     *
     * @param question the value for JXHD_SEL.question
     *
     * @abatorgenerated Mon Sep 29 15:15:08 CST 2014
     */
    public void setQuestion(String question) {
        this.question = question;
    }
}