package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class JXHD_QuestionPaper extends BaseDomain {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.ID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.shijuanID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private Integer shijuanid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.QuestionID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private Integer questionid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.QuestionType
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private String questiontype;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.chuti_man
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private String chutiMan;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.chuti_time
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private Date chutiTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.dati_man
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private String datiMan;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.dati_time
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private Date datiTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.UserAnswer
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private String useranswer;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.score
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private Double score;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.Commence
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private Double commence;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.status
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column JXHD_QuestionPaper.questionOrders
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	private String questionorders;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.ID
	 * @return  the value of JXHD_QuestionPaper.ID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.ID
	 * @param id  the value for JXHD_QuestionPaper.ID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.shijuanID
	 * @return  the value of JXHD_QuestionPaper.shijuanID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public Integer getShijuanid() {
		return shijuanid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.shijuanID
	 * @param shijuanid  the value for JXHD_QuestionPaper.shijuanID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setShijuanid(Integer shijuanid) {
		this.shijuanid = shijuanid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.QuestionID
	 * @return  the value of JXHD_QuestionPaper.QuestionID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public Integer getQuestionid() {
		return questionid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.QuestionID
	 * @param questionid  the value for JXHD_QuestionPaper.QuestionID
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setQuestionid(Integer questionid) {
		this.questionid = questionid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.QuestionType
	 * @return  the value of JXHD_QuestionPaper.QuestionType
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public String getQuestiontype() {
		return questiontype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.QuestionType
	 * @param questiontype  the value for JXHD_QuestionPaper.QuestionType
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setQuestiontype(String questiontype) {
		this.questiontype = questiontype;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.chuti_man
	 * @return  the value of JXHD_QuestionPaper.chuti_man
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public String getChutiMan() {
		return chutiMan;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.chuti_man
	 * @param chutiMan  the value for JXHD_QuestionPaper.chuti_man
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setChutiMan(String chutiMan) {
		this.chutiMan = chutiMan;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.chuti_time
	 * @return  the value of JXHD_QuestionPaper.chuti_time
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public Date getChutiTime() {
		return chutiTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.chuti_time
	 * @param chutiTime  the value for JXHD_QuestionPaper.chuti_time
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setChutiTime(Date chutiTime) {
		this.chutiTime = chutiTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.dati_man
	 * @return  the value of JXHD_QuestionPaper.dati_man
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public String getDatiMan() {
		return datiMan;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.dati_man
	 * @param datiMan  the value for JXHD_QuestionPaper.dati_man
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setDatiMan(String datiMan) {
		this.datiMan = datiMan;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.dati_time
	 * @return  the value of JXHD_QuestionPaper.dati_time
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public Date getDatiTime() {
		return datiTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.dati_time
	 * @param datiTime  the value for JXHD_QuestionPaper.dati_time
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setDatiTime(Date datiTime) {
		this.datiTime = datiTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.UserAnswer
	 * @return  the value of JXHD_QuestionPaper.UserAnswer
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public String getUseranswer() {
		return useranswer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.UserAnswer
	 * @param useranswer  the value for JXHD_QuestionPaper.UserAnswer
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setUseranswer(String useranswer) {
		this.useranswer = useranswer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.score
	 * @return  the value of JXHD_QuestionPaper.score
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public Double getScore() {
		return score;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.score
	 * @param score  the value for JXHD_QuestionPaper.score
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setScore(Double score) {
		this.score = score;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.Commence
	 * @return  the value of JXHD_QuestionPaper.Commence
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public Double getCommence() {
		return commence;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.Commence
	 * @param commence  the value for JXHD_QuestionPaper.Commence
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setCommence(Double commence) {
		this.commence = commence;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.status
	 * @return  the value of JXHD_QuestionPaper.status
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.status
	 * @param status  the value for JXHD_QuestionPaper.status
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column JXHD_QuestionPaper.questionOrders
	 * @return  the value of JXHD_QuestionPaper.questionOrders
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public String getQuestionorders() {
		return questionorders;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column JXHD_QuestionPaper.questionOrders
	 * @param questionorders  the value for JXHD_QuestionPaper.questionOrders
	 * @abatorgenerated  Thu Nov 06 12:54:10 CST 2014
	 */
	public void setQuestionorders(String questionorders) {
		this.questionorders = questionorders;
	}
}