package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;

public class JXHD_NOTSEL extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_NOTSEL.ID
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_NOTSEL.answer
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    private String answer;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_NOTSEL.score
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    private Double score;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_NOTSEL.teacherID
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    private Integer teacherid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_NOTSEL.QuesDifficult
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    private String quesdifficult;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_NOTSEL.questionType
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    private String questiontype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_NOTSEL.questionOrders
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    private String questionorders;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column JXHD_NOTSEL.question
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    private String question;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_NOTSEL.ID
     *
     * @return the value of JXHD_NOTSEL.ID
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_NOTSEL.ID
     *
     * @param id the value for JXHD_NOTSEL.ID
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_NOTSEL.answer
     *
     * @return the value of JXHD_NOTSEL.answer
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_NOTSEL.answer
     *
     * @param answer the value for JXHD_NOTSEL.answer
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_NOTSEL.score
     *
     * @return the value of JXHD_NOTSEL.score
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_NOTSEL.score
     *
     * @param score the value for JXHD_NOTSEL.score
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_NOTSEL.teacherID
     *
     * @return the value of JXHD_NOTSEL.teacherID
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_NOTSEL.teacherID
     *
     * @param teacherid the value for JXHD_NOTSEL.teacherID
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_NOTSEL.QuesDifficult
     *
     * @return the value of JXHD_NOTSEL.QuesDifficult
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public String getQuesdifficult() {
        return quesdifficult;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_NOTSEL.QuesDifficult
     *
     * @param quesdifficult the value for JXHD_NOTSEL.QuesDifficult
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public void setQuesdifficult(String quesdifficult) {
        this.quesdifficult = quesdifficult;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_NOTSEL.questionType
     *
     * @return the value of JXHD_NOTSEL.questionType
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public String getQuestiontype() {
        return questiontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_NOTSEL.questionType
     *
     * @param questiontype the value for JXHD_NOTSEL.questionType
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public void setQuestiontype(String questiontype) {
        this.questiontype = questiontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_NOTSEL.questionOrders
     *
     * @return the value of JXHD_NOTSEL.questionOrders
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public String getQuestionorders() {
        return questionorders;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_NOTSEL.questionOrders
     *
     * @param questionorders the value for JXHD_NOTSEL.questionOrders
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public void setQuestionorders(String questionorders) {
        this.questionorders = questionorders;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column JXHD_NOTSEL.question
     *
     * @return the value of JXHD_NOTSEL.question
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column JXHD_NOTSEL.question
     *
     * @param question the value for JXHD_NOTSEL.question
     *
     * @abatorgenerated Mon Sep 29 15:11:42 CST 2014
     */
    public void setQuestion(String question) {
        this.question = question;
    }
}