package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class leave extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.leave_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Integer leaveId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.student_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private String studentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.teacher_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.content
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private String content;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.from_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Date fromTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.to_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Date toTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.review_type
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Integer reviewType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.review_content
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private String reviewContent;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.review_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Date reviewTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.review_teacher_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Integer reviewTeacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.create_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column leave.leave_type
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    private Integer leaveType;
    
    private String className;

    public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.leave_id
     *
     * @return the value of leave.leave_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Integer getLeaveId() {
        return leaveId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.leave_id
     *
     * @param leaveId the value for leave.leave_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setLeaveId(Integer leaveId) {
        this.leaveId = leaveId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.student_id
     *
     * @return the value of leave.student_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.student_id
     *
     * @param studentId the value for leave.student_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.teacher_id
     *
     * @return the value of leave.teacher_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.teacher_id
     *
     * @param teacherId the value for leave.teacher_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.content
     *
     * @return the value of leave.content
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.content
     *
     * @param content the value for leave.content
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.from_time
     *
     * @return the value of leave.from_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Date getFromTime() {
        return fromTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.from_time
     *
     * @param fromTime the value for leave.from_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setFromTime(Date fromTime) {
        this.fromTime = fromTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.to_time
     *
     * @return the value of leave.to_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Date getToTime() {
        return toTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.to_time
     *
     * @param toTime the value for leave.to_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setToTime(Date toTime) {
        this.toTime = toTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.review_type
     *
     * @return the value of leave.review_type
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Integer getReviewType() {
        return reviewType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.review_type
     *
     * @param reviewType the value for leave.review_type
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setReviewType(Integer reviewType) {
        this.reviewType = reviewType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.review_content
     *
     * @return the value of leave.review_content
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public String getReviewContent() {
        return reviewContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.review_content
     *
     * @param reviewContent the value for leave.review_content
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setReviewContent(String reviewContent) {
        this.reviewContent = reviewContent;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.review_time
     *
     * @return the value of leave.review_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Date getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.review_time
     *
     * @param reviewTime the value for leave.review_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.review_teacher_id
     *
     * @return the value of leave.review_teacher_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Integer getReviewTeacherId() {
        return reviewTeacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.review_teacher_id
     *
     * @param reviewTeacherId the value for leave.review_teacher_id
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setReviewTeacherId(Integer reviewTeacherId) {
        this.reviewTeacherId = reviewTeacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.create_time
     *
     * @return the value of leave.create_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.create_time
     *
     * @param createTime the value for leave.create_time
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column leave.leave_type
     *
     * @return the value of leave.leave_type
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public Integer getLeaveType() {
        return leaveType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column leave.leave_type
     *
     * @param leaveType the value for leave.leave_type
     *
     * @abatorgenerated Tue Mar 10 15:40:23 CST 2015
     */
    public void setLeaveType(Integer leaveType) {
        this.leaveType = leaveType;
    }
}