package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class notice extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.notic_id
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer noticeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.title
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String title;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.update_time
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.class_id
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer classId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.mime_type
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String mimeType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.link_type
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer linkType;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.have_photo
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer havePhoto;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.pub_it
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer pubIt;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.link_url
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String linkUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.reportable
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer reportable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.ImageNews
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer imagenews;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.permission
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String permission;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.Inherit_Permi
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String inheritPermi;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.Deleted
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer deleted;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.Template
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String template;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.Publisher
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String publisher;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.Showorder
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer showorder;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.ZjepbNewsId
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer zjepbnewsid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.success_import
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private Integer successImport;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.attachFileUrl
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String attachfileurl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column notice.body
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    private String body;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.notic_id
     *
     * @return the value of notice.notic_id
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.notic_id
     *
     * @param noticId the value for notice.notic_id
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.title
     *
     * @return the value of notice.title
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.title
     *
     * @param title the value for notice.title
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.update_time
     *
     * @return the value of notice.update_time
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.update_time
     *
     * @param updateTime the value for notice.update_time
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.class_id
     *
     * @return the value of notice.class_id
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.class_id
     *
     * @param classId the value for notice.class_id
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.mime_type
     *
     * @return the value of notice.mime_type
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.mime_type
     *
     * @param mimeType the value for notice.mime_type
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.link_type
     *
     * @return the value of notice.link_type
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.link_type
     *
     * @param linkType the value for notice.link_type
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setLinkType(Integer linkType) {
        this.linkType = linkType;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.have_photo
     *
     * @return the value of notice.have_photo
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getHavePhoto() {
        return havePhoto;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.have_photo
     *
     * @param havePhoto the value for notice.have_photo
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setHavePhoto(Integer havePhoto) {
        this.havePhoto = havePhoto;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.pub_it
     *
     * @return the value of notice.pub_it
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getPubIt() {
        return pubIt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.pub_it
     *
     * @param pubIt the value for notice.pub_it
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setPubIt(Integer pubIt) {
        this.pubIt = pubIt;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.link_url
     *
     * @return the value of notice.link_url
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.link_url
     *
     * @param linkUrl the value for notice.link_url
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.reportable
     *
     * @return the value of notice.reportable
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getReportable() {
        return reportable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.reportable
     *
     * @param reportable the value for notice.reportable
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setReportable(Integer reportable) {
        this.reportable = reportable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.ImageNews
     *
     * @return the value of notice.ImageNews
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getImagenews() {
        return imagenews;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.ImageNews
     *
     * @param imagenews the value for notice.ImageNews
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setImagenews(Integer imagenews) {
        this.imagenews = imagenews;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.permission
     *
     * @return the value of notice.permission
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.permission
     *
     * @param permission the value for notice.permission
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.Inherit_Permi
     *
     * @return the value of notice.Inherit_Permi
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getInheritPermi() {
        return inheritPermi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.Inherit_Permi
     *
     * @param inheritPermi the value for notice.Inherit_Permi
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setInheritPermi(String inheritPermi) {
        this.inheritPermi = inheritPermi;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.Deleted
     *
     * @return the value of notice.Deleted
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.Deleted
     *
     * @param deleted the value for notice.Deleted
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.Template
     *
     * @return the value of notice.Template
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getTemplate() {
        return template;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.Template
     *
     * @param template the value for notice.Template
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setTemplate(String template) {
        this.template = template;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.Publisher
     *
     * @return the value of notice.Publisher
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.Publisher
     *
     * @param publisher the value for notice.Publisher
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.Showorder
     *
     * @return the value of notice.Showorder
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getShoworder() {
        return showorder;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.Showorder
     *
     * @param showorder the value for notice.Showorder
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setShoworder(Integer showorder) {
        this.showorder = showorder;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.ZjepbNewsId
     *
     * @return the value of notice.ZjepbNewsId
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getZjepbnewsid() {
        return zjepbnewsid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.ZjepbNewsId
     *
     * @param zjepbnewsid the value for notice.ZjepbNewsId
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setZjepbnewsid(Integer zjepbnewsid) {
        this.zjepbnewsid = zjepbnewsid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.success_import
     *
     * @return the value of notice.success_import
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public Integer getSuccessImport() {
        return successImport;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.success_import
     *
     * @param successImport the value for notice.success_import
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setSuccessImport(Integer successImport) {
        this.successImport = successImport;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.attachFileUrl
     *
     * @return the value of notice.attachFileUrl
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getAttachfileurl() {
        return attachfileurl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.attachFileUrl
     *
     * @param attachfileurl the value for notice.attachFileUrl
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setAttachfileurl(String attachfileurl) {
        this.attachfileurl = attachfileurl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column notice.body
     *
     * @return the value of notice.body
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column notice.body
     *
     * @param body the value for notice.body
     *
     * @abatorgenerated Tue Nov 25 18:01:56 CST 2014
     */
    public void setBody(String body) {
        this.body = body;
    }
}