package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;

public class student extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.student_id
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String studentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.class_id
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String classId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.name
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.sex
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String sex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.nation
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String nation;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.id_number
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String idNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.address
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.phone
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String phone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.hobby
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String hobby;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column student.speciality
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    private String speciality;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.student_id
     *
     * @return the value of student.student_id
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.student_id
     *
     * @param studentId the value for student.student_id
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.class_id
     *
     * @return the value of student.class_id
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.class_id
     *
     * @param classId the value for student.class_id
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setClassId(String classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.nation
     *
     * @return the value of student.nation
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.nation
     *
     * @param nation the value for student.nation
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.id_number
     *
     * @return the value of student.id_number
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.id_number
     *
     * @param idNumber the value for student.id_number
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.address
     *
     * @return the value of student.address
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.address
     *
     * @param address the value for student.address
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.phone
     *
     * @return the value of student.phone
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.phone
     *
     * @param phone the value for student.phone
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.hobby
     *
     * @return the value of student.hobby
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.hobby
     *
     * @param hobby the value for student.hobby
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column student.speciality
     *
     * @return the value of student.speciality
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column student.speciality
     *
     * @param speciality the value for student.speciality
     *
     * @abatorgenerated Tue Nov 25 17:25:38 CST 2014
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }
}