package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;

public class t_course_log extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_course_log.class_id
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    private Integer classId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_course_log.subject_id
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    private Integer subjectId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_course_log.end_time
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    private Date endTime;

    private Integer courseId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_course_log.from_time
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    private Date fromTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_course_log.user_id
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    private Integer userId;
    
    private String name;
    private String className;
    private String subjectName;
    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getClassName() {
		return className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public String getSubjectName() {
		return subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Integer getCourseId() {
		return courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	public Date getFromTime() {
		return fromTime;
	}

	public void setFromTime(Date fromTime) {
		this.fromTime = fromTime;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_course_log.class_id
     *
     * @return the value of t_course_log.class_id
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_course_log.class_id
     *
     * @param classId the value for t_course_log.class_id
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_course_log.subject_id
     *
     * @return the value of t_course_log.subject_id
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_course_log.subject_id
     *
     * @param subjectId the value for t_course_log.subject_id
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_course_log.end_time
     *
     * @return the value of t_course_log.end_time
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_course_log.end_time
     *
     * @param endTime the value for t_course_log.end_time
     *
     * @abatorgenerated Thu Jan 15 15:01:41 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}