package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;


public class T_SYS_ROLE_RESOURCE extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_ROLE_RESOURCE.ROLE_ID
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_ROLE_RESOURCE.RESOURCE_IDS
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    private String resourceIds;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_ROLE_RESOURCE.RESOURCE_ID
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    private String resourceId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_ROLE_RESOURCE.ROLE_ID
     *
     * @return the value of T_SYS_ROLE_RESOURCE.ROLE_ID
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_ROLE_RESOURCE.ROLE_ID
     *
     * @param roleId the value for T_SYS_ROLE_RESOURCE.ROLE_ID
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_ROLE_RESOURCE.RESOURCE_IDS
     *
     * @return the value of T_SYS_ROLE_RESOURCE.RESOURCE_IDS
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    public String getResourceIds() {
        return resourceIds;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_ROLE_RESOURCE.RESOURCE_IDS
     *
     * @param resourceIds the value for T_SYS_ROLE_RESOURCE.RESOURCE_IDS
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    public void setResourceIds(String resourceIds) {
        this.resourceIds = resourceIds;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_ROLE_RESOURCE.RESOURCE_ID
     *
     * @return the value of T_SYS_ROLE_RESOURCE.RESOURCE_ID
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_ROLE_RESOURCE.RESOURCE_ID
     *
     * @param resourceId the value for T_SYS_ROLE_RESOURCE.RESOURCE_ID
     *
     * @abatorgenerated Fri Sep 25 11:54:03 CST 2015
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }
}