package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;


public class T_SYS_RESOURCE  extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.RES_ID
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private Integer resId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.RES_PID
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private String resPid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.RES_NAME
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private String resName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.RES_URL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private String resUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.RES_TARGET
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private String resTarget;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.RES_DESC
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private String resDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.IS_MENU
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private String isMenu;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.IS_URL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private String isUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_RESOURCE.IS_ACL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    private String isAcl;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.RES_ID
     *
     * @return the value of T_SYS_RESOURCE.RES_ID
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public Integer getResId() {
        return resId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.RES_ID
     *
     * @param resId the value for T_SYS_RESOURCE.RES_ID
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setResId(Integer resId) {
        this.resId = resId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.RES_PID
     *
     * @return the value of T_SYS_RESOURCE.RES_PID
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public String getResPid() {
        return resPid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.RES_PID
     *
     * @param resPid the value for T_SYS_RESOURCE.RES_PID
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setResPid(String resPid) {
        this.resPid = resPid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.RES_NAME
     *
     * @return the value of T_SYS_RESOURCE.RES_NAME
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public String getResName() {
        return resName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.RES_NAME
     *
     * @param resName the value for T_SYS_RESOURCE.RES_NAME
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setResName(String resName) {
        this.resName = resName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.RES_URL
     *
     * @return the value of T_SYS_RESOURCE.RES_URL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public String getResUrl() {
        return resUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.RES_URL
     *
     * @param resUrl the value for T_SYS_RESOURCE.RES_URL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setResUrl(String resUrl) {
        this.resUrl = resUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.RES_TARGET
     *
     * @return the value of T_SYS_RESOURCE.RES_TARGET
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public String getResTarget() {
        return resTarget;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.RES_TARGET
     *
     * @param resTarget the value for T_SYS_RESOURCE.RES_TARGET
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setResTarget(String resTarget) {
        this.resTarget = resTarget;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.RES_DESC
     *
     * @return the value of T_SYS_RESOURCE.RES_DESC
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public String getResDesc() {
        return resDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.RES_DESC
     *
     * @param resDesc the value for T_SYS_RESOURCE.RES_DESC
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setResDesc(String resDesc) {
        this.resDesc = resDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.IS_MENU
     *
     * @return the value of T_SYS_RESOURCE.IS_MENU
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public String getIsMenu() {
        return isMenu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.IS_MENU
     *
     * @param isMenu the value for T_SYS_RESOURCE.IS_MENU
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setIsMenu(String isMenu) {
        this.isMenu = isMenu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.IS_URL
     *
     * @return the value of T_SYS_RESOURCE.IS_URL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public String getIsUrl() {
        return isUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.IS_URL
     *
     * @param isUrl the value for T_SYS_RESOURCE.IS_URL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setIsUrl(String isUrl) {
        this.isUrl = isUrl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_RESOURCE.IS_ACL
     *
     * @return the value of T_SYS_RESOURCE.IS_ACL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public String getIsAcl() {
        return isAcl;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_RESOURCE.IS_ACL
     *
     * @param isAcl the value for T_SYS_RESOURCE.IS_ACL
     *
     * @abatorgenerated Fri Sep 25 11:31:53 CST 2015
     */
    public void setIsAcl(String isAcl) {
        this.isAcl = isAcl;
    }
}