package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;


public class T_SYS_PARAMETER extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_PARAMETER.ID
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_PARAMETER.PARAMETER_TYPE_ID
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    private String parameterTypeId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_PARAMETER.PARAMETER_VALUE
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    private String parameterValue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_PARAMETER.PARAMETER_NAME
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    private String parameterName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_PARAMETER.PARAMETER_DESC
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    private String parameterDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_PARAMETER.PARAMETER_TYPE_NAME
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    private String parameterTypeName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_PARAMETER.ID
     *
     * @return the value of T_SYS_PARAMETER.ID
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_PARAMETER.ID
     *
     * @param id the value for T_SYS_PARAMETER.ID
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_PARAMETER.PARAMETER_TYPE_ID
     *
     * @return the value of T_SYS_PARAMETER.PARAMETER_TYPE_ID
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public String getParameterTypeId() {
        return parameterTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_PARAMETER.PARAMETER_TYPE_ID
     *
     * @param parameterTypeId the value for T_SYS_PARAMETER.PARAMETER_TYPE_ID
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public void setParameterTypeId(String parameterTypeId) {
        this.parameterTypeId = parameterTypeId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_PARAMETER.PARAMETER_VALUE
     *
     * @return the value of T_SYS_PARAMETER.PARAMETER_VALUE
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public String getParameterValue() {
        return parameterValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_PARAMETER.PARAMETER_VALUE
     *
     * @param parameterValue the value for T_SYS_PARAMETER.PARAMETER_VALUE
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public void setParameterValue(String parameterValue) {
        this.parameterValue = parameterValue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_PARAMETER.PARAMETER_NAME
     *
     * @return the value of T_SYS_PARAMETER.PARAMETER_NAME
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public String getParameterName() {
        return parameterName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_PARAMETER.PARAMETER_NAME
     *
     * @param parameterName the value for T_SYS_PARAMETER.PARAMETER_NAME
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public void setParameterName(String parameterName) {
        this.parameterName = parameterName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_PARAMETER.PARAMETER_DESC
     *
     * @return the value of T_SYS_PARAMETER.PARAMETER_DESC
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public String getParameterDesc() {
        return parameterDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_PARAMETER.PARAMETER_DESC
     *
     * @param parameterDesc the value for T_SYS_PARAMETER.PARAMETER_DESC
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public void setParameterDesc(String parameterDesc) {
        this.parameterDesc = parameterDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_PARAMETER.PARAMETER_TYPE_NAME
     *
     * @return the value of T_SYS_PARAMETER.PARAMETER_TYPE_NAME
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public String getParameterTypeName() {
        return parameterTypeName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_PARAMETER.PARAMETER_TYPE_NAME
     *
     * @param parameterTypeName the value for T_SYS_PARAMETER.PARAMETER_TYPE_NAME
     *
     * @abatorgenerated Tue Sep 23 13:15:37 CST 2014
     */
    public void setParameterTypeName(String parameterTypeName) {
        this.parameterTypeName = parameterTypeName;
    }
}