package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;


public class T_SYS_ROLE extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_ROLE.ROLE_ID
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_ROLE.ROLE_NAME
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    private String roleName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_ROLE.ROLE_DESC
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    private String roleDesc;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column T_SYS_ROLE.ROLE_ORDER
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    private String roleOrder;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_ROLE.ROLE_ID
     *
     * @return the value of T_SYS_ROLE.ROLE_ID
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_ROLE.ROLE_ID
     *
     * @param roleId the value for T_SYS_ROLE.ROLE_ID
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_ROLE.ROLE_NAME
     *
     * @return the value of T_SYS_ROLE.ROLE_NAME
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_ROLE.ROLE_NAME
     *
     * @param roleName the value for T_SYS_ROLE.ROLE_NAME
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_ROLE.ROLE_DESC
     *
     * @return the value of T_SYS_ROLE.ROLE_DESC
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_ROLE.ROLE_DESC
     *
     * @param roleDesc the value for T_SYS_ROLE.ROLE_DESC
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column T_SYS_ROLE.ROLE_ORDER
     *
     * @return the value of T_SYS_ROLE.ROLE_ORDER
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    public String getRoleOrder() {
        return roleOrder;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column T_SYS_ROLE.ROLE_ORDER
     *
     * @param roleOrder the value for T_SYS_ROLE.ROLE_ORDER
     *
     * @abatorgenerated Fri Sep 25 11:30:01 CST 2015
     */
    public void setRoleOrder(String roleOrder) {
        this.roleOrder = roleOrder;
    }
}