package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;


public class t_user extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.user_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer userId;
    private Integer roleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.class_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer classId;
    private Integer gradeId;
    private Integer classNum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.title_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer titleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.department_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String departmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.is_teacher
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer isTeacher;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.name
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.login_name
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String loginName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.pwd
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String pwd;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.sex
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer sex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.nation
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String nation;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.id_number
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String idNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.address
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.phone
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String phone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.email
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.is_owner
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer isOwner;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.type
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.status
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.update_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.update_by
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String updateBy;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.expire_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String expireTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.login_count
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer loginCount;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.last_login_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Date lastLoginTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.online
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private Integer online;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.hobby
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String hobby;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.speciality
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String speciality;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.rev_1
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String rev1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column t_user.rev_2
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    private String rev2;
    
    private String ip;

    public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public Integer getGradeId() {
		return gradeId;
	}

	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	public Integer getClassNum() {
		return classNum;
	}

	public void setClassNum(Integer classNum) {
		this.classNum = classNum;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.class_id
     *
     * @return the value of t_user.class_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.class_id
     *
     * @param classId the value for t_user.class_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.title_id
     *
     * @return the value of t_user.title_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.title_id
     *
     * @param titleId the value for t_user.title_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.department_id
     *
     * @return the value of t_user.department_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.department_id
     *
     * @param departmentId the value for t_user.department_id
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.is_teacher
     *
     * @return the value of t_user.is_teacher
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getIsTeacher() {
        return isTeacher;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.is_teacher
     *
     * @param isTeacher the value for t_user.is_teacher
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setIsTeacher(Integer isTeacher) {
        this.isTeacher = isTeacher;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.login_name
     *
     * @return the value of t_user.login_name
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.login_name
     *
     * @param loginName the value for t_user.login_name
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.pwd
     *
     * @return the value of t_user.pwd
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.pwd
     *
     * @param pwd the value for t_user.pwd
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.sex
     *
     * @return the value of t_user.sex
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.sex
     *
     * @param sex the value for t_user.sex
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.nation
     *
     * @return the value of t_user.nation
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.nation
     *
     * @param nation the value for t_user.nation
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.id_number
     *
     * @return the value of t_user.id_number
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.id_number
     *
     * @param idNumber the value for t_user.id_number
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.address
     *
     * @return the value of t_user.address
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.address
     *
     * @param address the value for t_user.address
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.is_owner
     *
     * @return the value of t_user.is_owner
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getIsOwner() {
        return isOwner;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.is_owner
     *
     * @param isOwner the value for t_user.is_owner
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setIsOwner(Integer isOwner) {
        this.isOwner = isOwner;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.type
     *
     * @return the value of t_user.type
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.type
     *
     * @param type the value for t_user.type
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.update_time
     *
     * @return the value of t_user.update_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.update_time
     *
     * @param updateTime the value for t_user.update_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.update_by
     *
     * @return the value of t_user.update_by
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.update_by
     *
     * @param updateBy the value for t_user.update_by
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.expire_time
     *
     * @return the value of t_user.expire_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.expire_time
     *
     * @param expireTime the value for t_user.expire_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setExpireTime(String expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.login_count
     *
     * @return the value of t_user.login_count
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.login_count
     *
     * @param loginCount the value for t_user.login_count
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.last_login_time
     *
     * @return the value of t_user.last_login_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.last_login_time
     *
     * @param lastLoginTime the value for t_user.last_login_time
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.online
     *
     * @return the value of t_user.online
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public Integer getOnline() {
        return online;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.online
     *
     * @param online the value for t_user.online
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setOnline(Integer online) {
        this.online = online;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.hobby
     *
     * @return the value of t_user.hobby
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.hobby
     *
     * @param hobby the value for t_user.hobby
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.speciality
     *
     * @return the value of t_user.speciality
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getSpeciality() {
        return speciality;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.speciality
     *
     * @param speciality the value for t_user.speciality
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setSpeciality(String speciality) {
        this.speciality = speciality;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.rev_1
     *
     * @return the value of t_user.rev_1
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getRev1() {
        return rev1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.rev_1
     *
     * @param rev1 the value for t_user.rev_1
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setRev1(String rev1) {
        this.rev1 = rev1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column t_user.rev_2
     *
     * @return the value of t_user.rev_2
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public String getRev2() {
        return rev2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column t_user.rev_2
     *
     * @param rev2 the value for t_user.rev_2
     *
     * @abatorgenerated Tue Dec 16 08:36:38 CST 2014
     */
    public void setRev2(String rev2) {
        this.rev2 = rev2;
    }
    
}