package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;

public class teacher  extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.teacher_id
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.department_id
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String departmentId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.name
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.sex
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String sex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.nation
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String nation;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.id_number
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String idNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.position
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String position;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.address
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.phone
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String phone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column teacher.email
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    private String email;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.teacher_id
     *
     * @return the value of teacher.teacher_id
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.teacher_id
     *
     * @param teacherId the value for teacher.teacher_id
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.department_id
     *
     * @return the value of teacher.department_id
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.department_id
     *
     * @param departmentId the value for teacher.department_id
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.sex
     *
     * @return the value of teacher.sex
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.sex
     *
     * @param sex the value for teacher.sex
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.nation
     *
     * @return the value of teacher.nation
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.nation
     *
     * @param nation the value for teacher.nation
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.id_number
     *
     * @return the value of teacher.id_number
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.id_number
     *
     * @param idNumber the value for teacher.id_number
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.position
     *
     * @return the value of teacher.position
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.position
     *
     * @param position the value for teacher.position
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.address
     *
     * @return the value of teacher.address
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.address
     *
     * @param address the value for teacher.address
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.phone
     *
     * @return the value of teacher.phone
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.phone
     *
     * @param phone the value for teacher.phone
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column teacher.email
     *
     * @return the value of teacher.email
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column teacher.email
     *
     * @param email the value for teacher.email
     *
     * @abatorgenerated Tue Nov 25 17:28:08 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }
}