package com.dt.jxhd.domain;

import com.dt.jxhd.commons.domain.BaseDomain;

public class test_item extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.item_id
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private Integer itemId;
    private Integer gradeId;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.pic
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String picUrl;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.ChoiceA
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String choicea;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.ChoiceB
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String choiceb;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.ChoiceC
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String choicec;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.ChoiceD
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String choiced;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.ChoiceE
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String choicee;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.ChoiceF
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String choicef;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.ChoiceG
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String choiceg;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.ChoiceNum
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private Integer choicenum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.answer
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String answer;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.score
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private Double score;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.questionType
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String questiontype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column test_item.question
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    private String question;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.item_id
     *
     * @return the value of test_item.item_id
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public Integer getItemId() {
        return itemId;
    }

    public Integer getGradeId() {
		return gradeId;
	}

	public void setGradeId(Integer gradeId) {
		this.gradeId = gradeId;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.item_id
     *
     * @param itemId the value for test_item.item_id
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.pic
     *
     * @return the value of test_item.pic
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */

    public String getChoicea() {
        return choicea;
    }

    public String getPicUrl() {
		return picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.ChoiceA
     *
     * @param choicea the value for test_item.ChoiceA
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setChoicea(String choicea) {
        this.choicea = choicea;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.ChoiceB
     *
     * @return the value of test_item.ChoiceB
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getChoiceb() {
        return choiceb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.ChoiceB
     *
     * @param choiceb the value for test_item.ChoiceB
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setChoiceb(String choiceb) {
        this.choiceb = choiceb;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.ChoiceC
     *
     * @return the value of test_item.ChoiceC
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getChoicec() {
        return choicec;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.ChoiceC
     *
     * @param choicec the value for test_item.ChoiceC
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setChoicec(String choicec) {
        this.choicec = choicec;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.ChoiceD
     *
     * @return the value of test_item.ChoiceD
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getChoiced() {
        return choiced;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.ChoiceD
     *
     * @param choiced the value for test_item.ChoiceD
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setChoiced(String choiced) {
        this.choiced = choiced;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.ChoiceE
     *
     * @return the value of test_item.ChoiceE
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getChoicee() {
        return choicee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.ChoiceE
     *
     * @param choicee the value for test_item.ChoiceE
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setChoicee(String choicee) {
        this.choicee = choicee;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.ChoiceF
     *
     * @return the value of test_item.ChoiceF
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getChoicef() {
        return choicef;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.ChoiceF
     *
     * @param choicef the value for test_item.ChoiceF
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setChoicef(String choicef) {
        this.choicef = choicef;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.ChoiceG
     *
     * @return the value of test_item.ChoiceG
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getChoiceg() {
        return choiceg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.ChoiceG
     *
     * @param choiceg the value for test_item.ChoiceG
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setChoiceg(String choiceg) {
        this.choiceg = choiceg;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.ChoiceNum
     *
     * @return the value of test_item.ChoiceNum
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public Integer getChoicenum() {
        return choicenum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.ChoiceNum
     *
     * @param choicenum the value for test_item.ChoiceNum
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setChoicenum(Integer choicenum) {
        this.choicenum = choicenum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.answer
     *
     * @return the value of test_item.answer
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.answer
     *
     * @param answer the value for test_item.answer
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.score
     *
     * @return the value of test_item.score
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.score
     *
     * @param score the value for test_item.score
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.questionType
     *
     * @return the value of test_item.questionType
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getQuestiontype() {
        return questiontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.questionType
     *
     * @param questiontype the value for test_item.questionType
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setQuestiontype(String questiontype) {
        this.questiontype = questiontype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column test_item.question
     *
     * @return the value of test_item.question
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column test_item.question
     *
     * @param question the value for test_item.question
     *
     * @abatorgenerated Wed Nov 26 11:08:40 CST 2014
     */
    public void setQuestion(String question) {
        this.question = question;
    }
}