package com.dt.jxhd.domain;

public class title {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column title.title_id
     *
     * @abatorgenerated Mon Mar 30 13:26:29 CST 2015
     */
    private Integer titleId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column title.title_name
     *
     * @abatorgenerated Mon Mar 30 13:26:29 CST 2015
     */
    private String titleName;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column title.title_id
     *
     * @return the value of title.title_id
     *
     * @abatorgenerated Mon Mar 30 13:26:29 CST 2015
     */
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column title.title_id
     *
     * @param titleId the value for title.title_id
     *
     * @abatorgenerated Mon Mar 30 13:26:29 CST 2015
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column title.title_name
     *
     * @return the value of title.title_name
     *
     * @abatorgenerated Mon Mar 30 13:26:29 CST 2015
     */
    public String getTitleName() {
        return titleName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column title.title_name
     *
     * @param titleName the value for title.title_name
     *
     * @abatorgenerated Mon Mar 30 13:26:29 CST 2015
     */
    public void setTitleName(String titleName) {
        this.titleName = titleName;
    }
}