package com.dt.jxhd.domain;

import java.util.Date;

import com.dt.jxhd.commons.domain.BaseDomain;



public class userDetail extends BaseDomain {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.ID
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.login
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String login;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.pwd
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String pwd;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.GroupName
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String groupname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.name
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.company
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String company;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.duty
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String duty;
    
    private String sex;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.phone
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String phone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.mobileTel
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String mobiletel;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.fax
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String fax;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.email
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.address
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String address;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.comment
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private String comment;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.groupid
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    private Integer groupid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.userprv
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    private Integer userprv;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.usercid
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    private String usercid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.auditing
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    private Integer auditing;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.orders
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    private Integer orders;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.zjepUesrID
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    private Integer zjepuesrid;
    
    private String permission;
    
    private Date birth;
    
    private String zhicheng;
    
    private String gonghao;
    public Date getBirth() {
		return birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	public String getZhicheng() {
		return zhicheng;
	}

	public void setZhicheng(String zhicheng) {
		this.zhicheng = zhicheng;
	}

	public String getGonghao() {
		return gonghao;
	}

	public void setGonghao(String gonghao) {
		this.gonghao = gonghao;
	}

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column userDetail.zjepUesrID2
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */

    public String getPermission() {
		return permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.ID
     *
     * @return the value of userDetail.ID
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.ID
     *
     * @param id the value for userDetail.ID
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.login
     *
     * @return the value of userDetail.login
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.login
     *
     * @param login the value for userDetail.login
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.pwd
     *
     * @return the value of userDetail.pwd
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.pwd
     *
     * @param pwd the value for userDetail.pwd
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.GroupName
     *
     * @return the value of userDetail.GroupName
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.GroupName
     *
     * @param groupname the value for userDetail.GroupName
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.name
     *
     * @return the value of userDetail.name
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.name
     *
     * @param name the value for userDetail.name
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.company
     *
     * @return the value of userDetail.company
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.company
     *
     * @param company the value for userDetail.company
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.duty
     *
     * @return the value of userDetail.duty
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.duty
     *
     * @param duty the value for userDetail.duty
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setDuty(String duty) {
        this.duty = duty;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.phone
     *
     * @return the value of userDetail.phone
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.phone
     *
     * @param phone the value for userDetail.phone
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.mobileTel
     *
     * @return the value of userDetail.mobileTel
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getMobiletel() {
        return mobiletel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.mobileTel
     *
     * @param mobiletel the value for userDetail.mobileTel
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setMobiletel(String mobiletel) {
        this.mobiletel = mobiletel;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.fax
     *
     * @return the value of userDetail.fax
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.fax
     *
     * @param fax the value for userDetail.fax
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.email
     *
     * @return the value of userDetail.email
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.email
     *
     * @param email the value for userDetail.email
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.address
     *
     * @return the value of userDetail.address
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.address
     *
     * @param address the value for userDetail.address
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.comment
     *
     * @return the value of userDetail.comment
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.comment
     *
     * @param comment the value for userDetail.comment
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.groupid
     *
     * @return the value of userDetail.groupid
     *
     * @abatorgenerated Thu May 15 14:11:48 CST 2014
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.groupid
     *
     * @param groupid the value for userDetail.groupid
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.userprv
     *
     * @return the value of userDetail.userprv
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public Integer getUserprv() {
        return userprv;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.userprv
     *
     * @param userprv the value for userDetail.userprv
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public void setUserprv(Integer userprv) {
        this.userprv = userprv;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.usercid
     *
     * @return the value of userDetail.usercid
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public String getUsercid() {
        return usercid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.usercid
     *
     * @param usercid the value for userDetail.usercid
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public void setUsercid(String usercid) {
        this.usercid = usercid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.auditing
     *
     * @return the value of userDetail.auditing
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public Integer getAuditing() {
        return auditing;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.auditing
     *
     * @param auditing the value for userDetail.auditing
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public void setAuditing(Integer auditing) {
        this.auditing = auditing;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.orders
     *
     * @return the value of userDetail.orders
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.orders
     *
     * @param orders the value for userDetail.orders
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column userDetail.zjepUesrID
     *
     * @return the value of userDetail.zjepUesrID
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public Integer getZjepuesrid() {
        return zjepuesrid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column userDetail.zjepUesrID
     *
     * @param zjepuesrid the value for userDetail.zjepUesrID
     *
     * @abatorgenerated Thu May 15 14:11:49 CST 2014
     */
    public void setZjepuesrid(Integer zjepuesrid) {
        this.zjepuesrid = zjepuesrid;
    }

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

     
}